const anycities = async (query) => {
    const cities = [
    "Gijang", "Ganghwa-gun", "Ongjin", "Ulju", "Gapyeong",
    "Goyang", "Gwacheon", "Gwangmyeong-si", "Gwangju", "Guri",
    "Gunpo", "Gimpo-si", "Namyangju", "Dongducheon-si", "Bucheon",
    "Seongnam", "Suwon", "Siheung-si", "Ansan", "Anseong",
    "Anyang", "Yangju", "Yangpyeong-gun", "Yeoju", "Yeoncheon-gun",
    "Osan", "Yongin", "Uiwang", "Uijeongbu-si", "Icheon-si",
    "Paju", "Pyeongtaek", "Pocheon-si", "Hanam", "Hwaseong",
    "Gangneung", "Goseong", "Donghae-si", "Samcheok", "Sokcho",
    "Yanggu", "Yangyang", "Yeongwol-gun",
    
    "Wonju", "Inje", "Naju", "Damyang", 
    "Jeongseon-gun", "Cheorwon-gun", "Chuncheon", "Taebaek", "Pyeongchang-gun",
    "Hongcheon-gun", "Hwacheon", "Hoengseong-gun", "Danyang", "Yeongdong",
    "Okcheon", "Jecheon", "Cheongju", "Chungju", "Gyeryong-si",
    "Gongju", "Nonsan", "Boryeong", "Buyeo", "Seosan", 
    "Asan", "Yesan", "Cheonan", "Taean", "Hongseong",
    "Gochang", "Gunsan", "Gimje", "Namwon", "Muju",
    "Buan", "Sunchang", "Wanju", "Iksan", "Imsil",
    "Jangsu", "Jeonju", "Jinan", "Gokseong", "Gwangyang",

    "Mokpo", "Muan", "Boseong",
    "Suncheon", "Shinan", "Yeosu", "Yeonggwang", "Wando",
    "Jangseong", "Hampyeong", "Haenam", "Hwasun", "Gyeongsan",
    "Gyeongju", "Goryeong", "Gumi", "Gunwi", "Gimcheon",
    "Mungyeong", "Bonghwa", "Sangju", "Seongju", "Andong",
    "Yeongyang", "Yeongju", "Yecheon", "Uiseong", "Cheongdo",
    "Cheongsong", "Chilgok", "Pohang", "Goseong", "Namhae",
    "Sacheon", "Yangsan", "Uiryeong", "Jinju", "Changnyeong",
    "Changwon", "Hadong", "Haman", "Hamyang", "Hapcheon",

    "Abidjan",
    "Abu Dhabi",
    "Abuja",
    "Accra",
    "Addis Ababa",
    "Agra",
    "Ahmedabad",
    "Aleppo",
    "Alexandria",
    "Algiers",
    "Almaty",
    "Andorra la Vella",
    "Ankara",
    "Antananarivo",
    "Athens",
    "Apia",
    "Avarua",
    "Baghdad",
    "Baku",
    "Bamako",
    "Banda Aceh",
    "Bandar Seri Begawan",
    "Bandung",
    "Bangkok",
    "Bangui",
    "Banjul",
    "Barcelona",
    "Basseterre",
    "Beijing",
    "Beirut",
    "Bekasi",
    "Belem",
    "Belgrade",
    "Belmopan",
    "Belo Horizonte",
    "Bengaluru",
    "Berlin",
    "Bern",
    "Bishkek",
    "Brasilia",
    "Bratislava",
    "Brazzaville",
    "Bridgetown",
    "Budapest",
    "Buenos Aires",
    "Bujumbura",
    "Bursa",
    "Busan",
    "Cairo",
    "Cape Town",
    "Caracas",
    "Casablanca",
    "Castries",
    "Charlotte Amalie",
    "Chengdu",
    "Chennai",
    "Chicago",
    "Damascus",
    "Dar es Salaam",
    "Daegu",
    "Daejeon",
    "Delhi",
    "Denver",
    "Dhaka",
    "Dubai",
    "Dublin",
    "Durban",
    "Dushanbe",
    "Florence",
    "Fort-de-France",
    "Fortaleza",
    "Freetown",
    "Fukuoka",
    "Funafuti",
    "George Town",
    "Georgetown",
    "Gibraltar",
    "Gitega",
    "Giza",
    "Gimhae",
    "Guadalajara",
    "Guangzhou",
    "Guatemala City",
    "Guayaquil",
    "Gujranwala",
    "Gustavia",
    "Gwangju",
    "Hamburg",
    "Hanoi",
    "Harare",
    "Havana",
    "Helsinki",
    "Ho Chi Minh City",
    "Honiara",
    "Honolulu",
    "Houston",
    "Hyderabad",
    "Ibadan",
    "Incheon",
    "Islamabad",
    "Isfahan",
    "Istanbul",
    "Izmir",
    "Jaipur",
    "Jakarta",
    "Jeddah",
    "Jeju",
    "Jerusalem",
    "Johannesburg",
    "Juarez",
    "Juba",
    "Kabul",
    "Kaduna",
    "Kampala",
    "Kaohsiung",
    "Karachi",
    "Karaj",
    "Kathmandu",
    "Kharkiv",
    "Khartoum",
    "Khulna",
    "Kigali",
    "Kingsburg",
    "Kingston",
    "Kingstown",
    "Kinshasa",
    "Kobe",
    "Kolkata",
    "Kota Bharu",
    "Kowloon",
    "Kyoto",
    "Lagos",
    "Lahore",
    "La Paz",
    "Libreville",
    "Lilongwe",
    "Lima",
    "Lisbon",
    "Ljubljana",
    "Lome",
    "London",
    "Los Angeles",
    "Luanda",
    "Lubumbashi",
    "Lusaka",
    "Luxembourg",
    "Macau",
    "Madrid",
    "Majuro",
    "Makassar",
    "Malabo",
    "Male",
    "Mamoudzou",
    "Managua",
    "Manama",
    "Manaus",
    "Manila",
    "Maputo",
    "Maracaibo",
    "Maracay",
    "Mariehamn",
    "Marigot",
    "Maseru",
    "Mashhad",
    "Mbabane",
    "Mecca",
    "Medan",
    "Medellin",
    "Medina",
    "Melbourne",
    "Mexico City",
    "Miami",
    "Minsk",
    "Miryang",
    "Mogadishu",
    "Monaco",
    "Monrovia",
    "Montevideo",
    "Moscow",
    "Mosul",
    "Multan",
    "Mumbai",
    "Muscat",
    "N'Djamena",
    "Nagoya",
    "Nairobi",
    "Nanchong",
    "Nanjing",
    "Nassau",
    "Nay Pyi Taw",
    "New York",
    "Niamey",
    "Nicosia",
    "Nouakchott",
    "Noumea",
    "Novosibirsk",
    "Nuku'alofa",
    "Nur-Sultan",
    "Nuuk",
    "Oranjestad",
    "Orlando",
    "Osaka",
    "Oslo",
    "Ottawa",
    "Ouagadougou",
    "Pago Pago",
    "Palembang",
    "Palo Alto",
    "Panama",
    "Papeete",
    "Paramaribo",
    "Paris",
    "Perth",
    "Philadelphia",
    "Phnom Penh",
    "Phoenix",
    "Pisa",
    "Podgorica",
    "Port Louis",
    "Port Moresby",
    "Port-Vila",
    "Port-au-Prince",
    "Porto Alegre",
    "Porto-Novo",
    "Prague",
    "Praia",
    "Pretoria",
    "Pristina",
    "Puebla",
    "Pune",
    "Pyongyang",
    "Quezon City",
    "Quito",
    "Rabat",
    "Rawalpindi",
    "Recife",
    "Reykjavik",
    "Riga",
    "Rio de Janeiro",
    "Riyadh",
    "Road Town",
    "Rome",
    "Roseau",
    "Saint George's",
    "Saint Helier",
    "Saint John's",
    "Saint Peter Port",
    "Saint Petersburg",
    "Saint-Denis",
    "Saint-Pierre",
    "Saipan",
    "Salvador",
    "San Antonio",
    "San Diego",
    "San Francisco",
    "San Jose",
    "San Juan",
    "San Marino",
    "San Salvador",
    "Sanaa",
    "Santa Cruz de la Sierra",
    "Santiago",
    "Santo Domingo",
    "Sao Paulo",
    "Sao Tome",
    "Sapporo",
    "Sarajevo",
    "Seattle",
    "Semarang",
    "Seoul",
    "Sejong",
    "Shanghai",
    "Sharjah",
    "Shenzhen",
    "Singapore",
    "Skopje",
    "Sofia",
    "South Tangerang",
    "Soweto",
    "Stockholm",
    "Sucre",
    "Surabaya",
    "Surat",
    "Suva",
    "Sydney",
    "Tabriz",
    "Taipei",
    "Tallinn",
    "Tangerang",
    "Tarawa",
    "Tashkent",
    "Tbilisi",
    "Tegucigalpa",
    "Tehran",
    "Tel Aviv",
    "Thimphu",
    "Tianjin",
    "Tijuana",
    "Tirana",
    "Tokyo",
    "Toronto",
    "Ulan Bator",
    "Ulsan",
    "Vaduz",
    "Valencia",
    "Valletta",
    "Vancouver",
    "Victoria",
    "Vienna",
    "Vientiane",
    "Vilnius",
    "Warsaw",
    "Washington",
    "Wellington",
    "Willemstad",
    "Wiltshire",
    "Windhoek",
    "Wuhan",
    "Xi'an",
    "Yamoussoukro",
    "Yangon",
    "Yaounde",
    "Yekaterinburg",
    "Yerevan",
    "Yokohama",
    "Zagreb",
    "Zamboanga City",
    "Zanzibar City",
    "Zaporizhzhia",
    "Zaragoza",
    "Zaria",
    "Zibo",
    "Zunyi",
    "Zurich",
        ];
    
        const relatedCities = cities.filter(city => city.toLowerCase().startsWith(query.toLowerCase()));
    
        return relatedCities;
    }
    
    export { anycities };

    